src/Entity/Color.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ColorRepository")
 */
class Color
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=6)
     */
    private $hexColor;

    public function __construct(string $name, string $hexColor)
    {
        $this->name = $name;
        $this->hexColor = $hexColor;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getHexColor(): ?string
    {
        return $this->hexColor;
    }

    public function setHexColor(string $hexColor): self
    {
        $this->hexColor = $hexColor;

        return $this;
    }

    public function getRed(): string
    {
        return hexdec(substr($this->hexColor, 0, 2));
    }

    public function getGreen(): string
    {
        return hexdec(substr($this->hexColor, 2, 2));
    }

    public function getBlue(): string
    {
        return hexdec(substr($this->hexColor, 4, 2));
    }
}

src/Entity/Product.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProductRepository")
 */
class Product
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     * @Groups("product:read")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("product:read")
     * @Assert\NotBlank()
     */
    private $name;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @Groups("product:read")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=20)
     * @Assert\NotBlank
     */
    private $brand = 'Low End Luxury';

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $weight;

    /**
     * @ORM\Column(type="integer")
     * @Groups("product:read")
     * @Assert\GreaterThan(0)
     * @Assert\NotBlank()
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     * @Assert\GreaterThanOrEqual(0)
     */
    private $stockQuantity = 0;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="products")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotBlank
     */
    private $category;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Color")
     */
    private $colors;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $imageFilename = 'floppy-disc.png';

    /**
     * @ORM\OneToMany(targetEntity=Review::class, mappedBy="product", cascade={"remove"})
     */
    private $reviews;

    public function __construct()
    {
        $this->colors = new ArrayCollection();
        $this->reviews = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getBrand(): ?string
    {
        return $this->brand;
    }

    public function setBrand(?string $brand): self
    {
        $this->brand = $brand;

        return $this;
    }

    public function getWeight(): ?float
    {
        return $this->weight;
    }

    public function setWeight(?float $weight): self
    {
        $this->weight = $weight;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function getPriceString(): string
    {
        return (string) $this->price / 100;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getStockQuantity(): ?int
    {
        return $this->stockQuantity;
    }

    public function setStockQuantity(int $stockQuantity): self
    {
        $this->stockQuantity = $stockQuantity;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection|Color[]
     */
    public function getColors(): Collection
    {
        return $this->colors;
    }

    public function addColor(Color $color): self
    {
        if (!$this->colors->contains($color)) {
            $this->colors[] = $color;
        }

        return $this;
    }

    public function removeColor(Color $color): self
    {
        if ($this->colors->contains($color)) {
            $this->colors->removeElement($color);
        }

        return $this;
    }

    public function hasColors(): bool
    {
        return count($this->colors) > 0;
    }

    public function getImageFilename(): ?string
    {
        return $this->imageFilename;
    }

    public function setImageFilename(string $imageFilename): self
    {
        $this->imageFilename = $imageFilename;

        return $this;
    }

    /**
     * @Groups("product:read")
     */
    public function getImageUrl(): string
    {
        return sprintf('/uploads/products/'.$this->imageFilename);
    }

    /**
     * @return Collection|Review[]
     */
    public function getReviews(): Collection
    {
        return $this->reviews;
    }

    public function getAverageStars(): float
    {
        if (count($this->getReviews()) === 0) {
            return 0;
        }

        $totalRating = 0;
        // this is an inefficient way of doing this ;)
        foreach ($this->getReviews() as $review) {
            $totalRating += $review->getStars();
        }

        return round($totalRating / count($this->getReviews()), 1);
    }

    public function __toString(): string
    {
        return sprintf('%s ($%s)', $this->name, $this->getPriceString());
    }
}

src/Form/ProductType.php
<?php

namespace App\Form;

use App\Entity\Product;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProductType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('description')
            ->add('price')
            ->add('category')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Product::class,
        ]);
    }
}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Category;
use App\Entity\Product;
use App\Entity\Review;
use App\Form\AddItemToCartFormType;
use App\Form\ReviewForm;
use App\Repository\CategoryRepository;
use App\Repository\ProductRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;
use Symfony\UX\Turbo\Stream\TurboStreamResponse;

class ProductController extends AbstractController
{
    /**
     * @Route("/", name="app_homepage")
     * @Route("/category/{id}", name="app_category")
     */
    public function index(Request $request, CategoryRepository $categoryRepository, ProductRepository $productRepository, Category $category = null): Response
    {
        $searchTerm = $request->query->get('q');
        $products = $productRepository->search(
            $category,
            $searchTerm
        );

        if ($request->query->get('preview')) {
            return $this->render('product/_searchPreview.html.twig', [
                'products' => $products,
            ]);
        }

        return $this->render('product/index.html.twig', [
            'currentCategory' => $category,
            'categories' => $categoryRepository->findAll(),
            'products' => $products,
            'searchTerm' => $searchTerm
        ]);
    }

    /**
     * @Route("/product/{id}", name="app_product", methods={"GET"})
     */
    public function showProduct(Product $product, CategoryRepository $categoryRepository): Response
    {
        $addToCartForm = $this->createForm(AddItemToCartFormType::class, null, [
            'product' => $product
        ]);

        $reviewForm = null;
        if ($this->getUser()) {
            $reviewForm = $this->createForm(ReviewForm::class, new Review($this->getUser(), $product));
        }

        return $this->renderForm('product/show.html.twig', [
            'product' => $product,
            'currentCategory' => $product->getCategory(),
            'categories' => $categoryRepository->findAll(),
            'addToCartForm' => $addToCartForm,
            'reviewForm' => $reviewForm ?: null,
        ]);
    }

    /**
     * @Route("/product/{id}/reviews", name="app_product_reviews")
     */
    public function productReviews(Product $product, CategoryRepository $categoryRepository, Request $request, EntityManagerInterface $entityManager)
    {
        $reviewForm = null;

        if ($this->getUser()) {
            $reviewForm = $this->createForm(ReviewForm::class, new Review($this->getUser(), $product));
        }

        if ($request->isMethod('POST')) {
            $this->denyAccessUnlessGranted('ROLE_USER');

            $reviewForm->handleRequest($request);

            if ($reviewForm->isSubmitted() && $reviewForm->isValid()) {
                $entityManager->persist($reviewForm->getData());
                $entityManager->flush();

                $this->addFlash('review_success', 'Thanks for your review! I like you!');

                return $this->redirectToRoute('app_product_reviews', [
                    'id' => $product->getId(),
                ]);
            }
        }

        return $this->renderForm('product/reviews.html.twig', [
            'product' => $product,
            'currentCategory' => $product->getCategory(),
            'categories' => $categoryRepository->findAll(),
            'reviewForm' => $reviewForm?: null,
        ]);
    }

    /**
     * @Route("/you-won")
     */
    public function youWon()
    {
        return $this->render('product/winner.html.twig');
    }
}

templates/product/_cart_add_controls.html.twig
<turbo-frame
    id="add-to-cart-controls"
    data-turbo-form-redirect="true"
>
{{ form_start(addToCartForm, {
    attr: { class: 'cart-add-controls d-flex align-items-center justify-content-baseline' }
}) }}
    {% if addToCartForm.color is defined %}
        <div
            {{ stimulus_controller('color-square', {
                colorId: addToCartForm.vars.data.product.colors[1].id
            }) }}
        >
            {{ form_widget(addToCartForm.color, {
                attr: { 'data-color-square-target': 'select' }
            }) }}

            {% for color in addToCartForm.vars.data.product.colors %}
                <button
                    class="color-square btn"
                    type="button"
                    data-action="color-square#selectColor"
                    data-color-square-target="colorSquare"
                    data-color-id="{{ color.id }}"
                    style="background-color: rgb({{ color.red }}, {{ color.green }}, {{ color.blue }});"
                ></button>
            {% endfor %}
        </div>
    {% endif %}

    {{ form_widget(addToCartForm.quantity, {
        attr: { class: 'mx-3' }
    }) }}

    <button class="btn btn-info btn-sm" formnovalidate>
        +
    </button>
{{ form_end(addToCartForm) }}

<div>
    {{ form_errors(addToCartForm) }}
    {% if addToCartForm.color is defined %}
        {{ form_errors(addToCartForm.color) }}
    {% endif %}
    {{ form_errors(addToCartForm.quantity) }}
</div>
</turbo-frame>

templates/product/_categoriesSidebar.html.twig
<div class="p-3 mb-5 component-light">
    <h5 class="text-center">
        Categories
    </h5>
    <ul class="nav flex-column mb4">
        <li class="nav-item">
            <a href="{{ path('app_homepage') }}" class="nav-link {{ not currentCategory|default ? 'selected' }}">
                All Products
            </a>
        </li>
        {% for category in categories %}
            <li class="nav-item">
                <a
                    href="{{ path('app_category', { id: category.id }) }}"
                    class="nav-link {{ currentCategory|default is same as category ? 'selected' }}"
                >
                    {{ category.name }}
                </a>
            </li>
        {% endfor %}
    </ul>
</div>

templates/product/_quickStats.html.twig
<strong>{{ product.priceString|format_currency('USD') }}</strong>
<br>
<strong>{{ product.reviews|length }}</strong> Reviews
<br/>
<strong>{{ product.averageStars }}/5</strong><i class="fas fa-star ms-2"></i>

templates/product/_review.html.twig
<div
    id="product-review-{{ review.id }}"
    class="component-light my-3 p-3"
    {% if isNew|default(false) %}
        {{ stimulus_controller('streamed-item', {
            className: 'streamed-new-item'
        }) }}
    {% endif %}
    {% if isRemoved|default(false) %}
        {{ stimulus_controller('streamed-item', {
            className: 'streamed-removed-item',
            removeElement: true
        }) }}
    {% endif %}
>
    <p><i class="fas fa-user-circle me-2"></i>{{ review.owner.email }} <i class="fas fa-star ms-4"></i> {{ review.stars }}/5</p>
    <div>
        {{ review.content }}
    </div>
</div>

templates/product/_reviews.html.twig
<div {{ turbo_stream_listen('App\\Entity\\Review') }}></div>

{{ include('product/_reviews_list.html.twig') }}

<hr>

<turbo-frame id="product-reviews-form">

{% for flash in app.flashes('review_success') %}
    {{ include('_toast.html.twig', {
        title: 'Success!',
        body: flash
    }) }}
{% endfor %}

{% if reviewForm|default(false) %}
    <h4>Post your own review</h4>
    {{ form_start(reviewForm, {
        'action': path('app_product_reviews', { id: product.id })
    }) }}
        {{ form_row(reviewForm.stars) }}
        {{ form_row(reviewForm.content) }}

        <button class="btn btn-primary" formnovalidate>Add Review</button>
    {{ form_end(reviewForm) }}
{% elseif not is_granted('ROLE_USER') %}
    <p><a href="{{ path('app_login') }}" data-turbo-frame="_top">Log in</a> to post your review</p>
{% else %}
    <div class="alert alert-success">
        Thanks for your "real" review you "human" 😉!
    </div>

    <a href="{{ path('app_product_reviews', {
        id: product.id
    }) }}">Love the product *that* much? Add another review!</a>
{% endif %}
</turbo-frame>

templates/product/_reviews_list.html.twig
<div id="product-{{ product.id }}-review-list">
{% for review in product.reviews %}
    {{ include('product/_review.html.twig') }}
{% else %}
    <p>This product has not been reviewed yet!</p>
{% endfor %}
</div>

templates/product/_searchPreview.html.twig
<div class="list-group">
    {% for product in products %}
        <a
            role="option"
            class="list-group-item list-group-item-action"
            href="{{ path('app_product', { id: product.id }) }}"
        >
            <div class="d-flex align-items-center justify-content-between">
                <div>
                    <img
                        alt="{{ product.name }}"
                        src="{{ asset('/uploads/products/'~product.imageFilename) }}"
                        class="rounded"
                    >
                    <span class="px-1">{{ product.name }}</span>
                </div>
                <em>{{ product.priceString|format_currency('USD') }}</em>
            </div>
        </a>
    {% else %}
        <div class="list-group-item" role="option" aria-disabled="true">No results found!</div>
    {% endfor %}
</div>

templates/product/index.html.twig
{% extends 'product/productBase.html.twig' %}

{% block productAboveRow %}
    <div class="p-3 mb-4 text-center" data-controller="counter" style="background-color: #efefee;">
        <button
            data-action="counter#increment"
            class="btn btn-success btn-sm me-3"
        >
            Click for a chance to win!
        </button>

        You've entered the contest
        <span data-counter-target="count">0</span>
        times!
    </div>
{% endblock %}

{% block productBody %}
    <div class="row">
        <div class="col-3">
            <h1>
                {% if currentCategory %}
                    {{ currentCategory.name }}
                {% else %}
                    All Products
                {% endif %}
            </h1>
        </div>
        <div class="col-9">
            <form>
                <div
                    class="input-group"
                    {{ stimulus_controller({
                        'autocomplete': {
                            url: path('app_homepage', { preview: 1 }),
                            skipHiddenProperty: true
                        },
                        'autocomplete-transition': {}
                    }) }}
                    data-action="toggle->autocomplete-transition#toggle"
                >
                    <input
                        name="q"
                        value="{{ searchTerm }}"
                        placeholder="Search products..."
                        type="search"
                        class="form-control"
                        data-autocomplete-target="input"
                    >

                    <div
                        class="search-preview"
                        data-autocomplete-target="results"
                        data-autocomplete-transition-target="results"
                    ></div>
                </div>
            </form>
        </div>
    </div>
    <div class="row mt-4">
        {% for product in products %}
            <div class="col-xs-12 col-6 mb-2 pb-2">
                <div class="component-light">
                    <div class="product-image">
                        <a href="{{ path('app_product', { id: product.id }) }}">
                            <img
                                alt="{{ product.name }}"
                                src="{{ asset('/uploads/products/'~product.imageFilename) }}"
                                class="d-block mb-2"
                            >
                        </a>
                        <div class="d-flex justify-content-between px-2 pt-3 mb-2">
                            <h3>
                                <a href="{{ path('app_product', { id: product.id }) }}">
                                    {{ product.name }}
                                </a>
                            </h3>
                            <p>{{ product.averageStars }}/5<i class="fas fa-star ms-2"></i></p>
                        </div>
                    </div>
                    <div class="px-2 my-3 d-flex justify-content-between">
                        <p class="p-0 d-inline">
                            <strong>{{ product.priceString|format_currency('USD') }}</strong>
                        </p>
                        <a href="{{ path('app_product', { id: product.id }) }}" class="btn btn-info">View Product</a>
                    </div>
                </div>
                <hr>
                <div class="px-2 pb-2">
                    <small>brought to you by {{ product.brand }}</small>
                </div>
            </div>
        {% else %}
            <div class="col-12">
                <h5 class="ml-4 mt-4" >
                    Whoopsie Daisy, no products found!
                </h5>
            </div>
        {% endfor %}
    </div>

    <div class="row">
        <span class="p-3">
            Shipping takes 10-13 weeks, and products probably won't work
        </span>
    </div>
{% endblock %}

templates/product/productBase.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container mt-4">
        {% block productAboveRow %}{% endblock %}
        <div class="row">
            <aside class="col-12 col-md-3 order-2 order-md-1">
                {{ include('product/_categoriesSidebar.html.twig') }}

                <turbo-frame id="weather_widget" src="{{ path('app_weather') }}"></turbo-frame>
            </aside>

            <div class="col-12 col-md-9 product-show order-1 order-md-2">
                {% block productBody %}{% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

templates/product/reviews.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container-fluid mt-4">
        <div class="row">
            <aside class="col-xs-12 col-3">
                {{ include('product/_categoriesSidebar.html.twig') }}
            </aside>

            <div class="col-xs-12 col-9 product-show">
                <h1>
                    Reviews for
                    <a href="{{ path('app_product', { id: product.id }) }}">
                        {{ product.name }}
                    </a>
                </h1>

                {{ include('product/_reviews.html.twig') }}
            </div>
        </div>
    </div>
{% endblock %}

templates/product/show.html.twig
{% extends 'product/productBase.html.twig' %}

{% block productBody %}
    <div id="product-{{ product.id }}-toasts"></div>

    <turbo-frame id="product-info" target="_top" class="row pt-3 product-show">
        <div class="col-4">
            <img
                alt="{{ product.name }}"
                src="{{ asset('/uploads/products/'~product.imageFilename) }}"
                class="d-block"
            >
            <div class="p-2">
                <small>brought to you by </small>
                <small class="d-inline">{{ product.brand }}</small>
            </div>
        </div>
        <div class="col-8 px-3">
            <h1>
                {{ product.name }}
                {% if is_granted('ROLE_ADMIN') %}
                    <a
                        href="{{ path('product_admin_edit', {
                            id: product.id
                        }) }}"
                        class="btn btn-sm btn-secondary"
                        data-turbo-frame="product-info"
                    >Edit</a>
                {% endif %}
            </h1>
            <div>
                {{ product.description }}
            </div>
            <div class="p-3 mt-4 d-flex justify-content-between flex-wrap flex-lg-nowrap">
                <div id="product-{{ product.id }}-quick-stats">
                    {{ include('product/_quickStats.html.twig') }}
                </div>
                <div>
                    {{ include('product/_cart_add_controls.html.twig') }}
                </div>
            </div>
        </div>
    </turbo-frame>

    <hr>

    <h3>Reviews</h3>

    {{ include('product/_reviews.html.twig') }}
{% endblock %}

templates/product/winner.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="container text-center" style="margin-top: 100px; margin-bottom: 150px;">
    <h1 class="mt-5">Congratulations!</h1>

    <p>You have won your very own Tamagotchi - keep pressing those buttons to care for it daily!</p>

    <img src="{{ asset('images/tamagotchi.png' ) }}"
            width="200"
            height="200"
            alt="You won a tamagotchi"
    >
</div>
{% endblock %}